### ISSUE TITLE
Cannot open a .tsv file

### ISSUE THREAD

**Issue by Xyz00777** [ONLYOFFICE/DocumentServer#1052]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If you open a .tsv file the message "File format is not supported" shows but when I open a .csv file the default delimiter option is tabulator....

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. start the programm
2. open a tsv file

**What is the expected behavior?**
The same as the current behaviour when you open a csv file.
And if you open a CSV, a *Comma* Seperated Value file, the default delimiter should be comma or more options, like LibreOffice.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
5.6.4.20

**Comment by ShockwaveNN** [comment]
Moving this issue to DocumentServer repo, since it's our base product and problem actual there too

**Comment by janxkoci** [comment]
FYI: It's possible to open TSV (Tab-separated values) file, by changing the file extension to `.csv` (as a Comma-separated values file). OnlyOffice then allows opening the file and asks about separator, where Tab can be selected and the file is correctly opened.

However note that saving the file will result in conversion to CSV, i.e. comma-separated values file.

**Comment by jondo** [comment]
Btw., the extension `.csv` can also generally mean "character separated values", so you don't need a different file extension for tabs.

**Comment by janxkoci** [comment]
Interesting, I've never heard about this meaning of the `.csv` extension, but it seems [you're right](https://en.wikipedia.org/wiki/Comma-separated_values). However with plain text files, the file extensions are more of a _convention_ than a requirement. For instance, LibreOffice lets me open `.txt` files in Calc by default, expecting a `.csv` formatted file.

**Comment by janxkoci** [comment]
Is there any progress on this?

Let me summarize:

- OnlyOffice has a _strong aversion_ towards the TSV extension. [^1]
- OnlyOffice _can_ open TSV files (if you rename them).

Since other office suits accept TSV as valid file extension, I think it would be appropriate for OO to also accept it. Especially since it has no problem opening the underlying format.

[^1]: OO hates TSV extension to the point that it _freezes_ if I try to drag-n-drop a TSV file onto an OO window. Killing the app and renaming the file to CSV shows no such issue. FWIW I installed OO as a flatpak on Ubuntu.

**Comment by janxkoci** [comment]
> so you don't need a different file extension for tabs.

I guess I don't _need_ it, but it's really convenient for me to have it. I use commandline like all the time, as a scientist. This is why I use plain-text spreadsheets so much in the first place. I need to load them to `R` or extract something with `awk` et al on a daily basis. In the majority of scenarios TSVs are more easy to work with for me than CSVs and I use the extension to inform me up front which format am I facing at the moment. Renaming all my files to CSV would be quite a downgrade for my workflow and an extra burden for my brain to worry about. Less trial-and-error cycles, which I have plenty of already in my job.

Those are my 2cents.

**Comment by janxkoci** [comment]
**Is there anything that can be done to move this forward?**

All we need here is that files with the TSV extension are treated exactly as CSV files - i.e. open with dialog to select encoding and separator. At most you could change the preselected separator, but even without it the experience would be a _**massive**_ improvement over the current behaviour (i.e. a show-stopping error in my face).

These are plain text files, nothing complicated. In fact, Libre Office lets me open _any_ plaintext file in Calc (their spreadsheet app), no matter the extension. Simply because many other plaintext formats are just a fancier version of TSV or CSV (e.g. some 70% of formats in bioinformatics are just plain TSV with fancy headers) - but renaming VCF or SAM or BED or GFF all to CSV will help nobody. Same for TSV. So why pretend that the issue is complicated - the only related complicated thing is standards-compliant CSV with quotes, which is already supported. Also plain TSV is already supported.

The _only_ thing _really_ broken here is that a `.tsv` at the end of my file name will break all hell loose, for no good reason.

**Comment by Rita-Bubnova** [comment]
@janxkoci, Sorry I'm just a QA specialist, I'm not in a position to guarantee any estimates. You better contact sales@onlyoffice.com.

**Comment by silkskier** [comment]
> **Is there anything that can be done to move this forward?**


I'm not sure, if I'm right, but it's highly probable, that addition of <10 lines of code in https://github.com/ONLYOFFICE/core/ repository may be enough to solve the issue. I'll try to build OnlyOffice in it's current state from source, and if I succeed I'll try to add the changes to make it succeed in loading tsv files.

If it will work I can try making a commit, which *may* be merged, but currently I do not really understand how the code is structured here, so I have no idea, if it's really that simple. Anyway it's weird how it didn't get fixed in the recent 2 years.

**Comment by janxkoci** [comment]
In the meantime, I also noticed that I can open the files just fine from the Data tab in ribbon, using the get data from local CSV/TXT file, then filtering to all file types in the dialog and selecting e.g. a TSV file. After that there is even a nice preview to check your separator etc, which is very nice and should be in the default open CSV dialog as well IMHO (other users asked for this exact feature here on github too).

**Comment by 1bardesign** [comment]
This is still happening :) Hoping for a fix before long; it really just needs to open tsv files with the existing csv code as far as i can tell.

**Comment by jakob1379** [comment]
> In the meantime, I also noticed that I can open the files just fine from the Data tab in ribbon, using the get data from local CSV/TXT file, then filtering to all file types in the dialog and selecting e.g. a TSV file. After that there is even a nice preview to check your separator etc, which is very nice and should be in the default open CSV dialog as well IMHO (other users asked for this exact feature here on github too).

Is there a way to force OnlyOffice to just use this as the default way to read datafiles?
It is much more convenient than that regular view of opening files, and combine that with being able to open any text-file and only using the extension to guess the delimiter would be amazing!

**Comment by BenDo85** [comment]
Hello, bumping this issue. I'm getting :

> File format is not supported

When I try to open a .tsv file

Have a nice day

**Comment by k-soomro** [comment]
Just ran into this issue as well.

**Comment by ElenaMaaya** [comment]
Hello! I have a good news! This issue will be fixed in the next release ([commit](https://github.com/ONLYOFFICE/core/commit/fba3767e367a113a1b247f1bd9aee79428c180f2)).
Please keep checking for updates.

**Comment by Rita-Bubnova** [comment]
DocumentServer v9.3.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
