### ISSUE TITLE
Copy and paste does not work in Firefox 94

### ISSUE THREAD

**Issue by alci63** [ONLYOFFICE/DocumentServer#1502]
BUG

Copy and paste, either with Ctrl+C Ctrl+V or with icons does not work in Firefox (nothing happens, except for the informative popup that explains how copy and paste work).

Create (or open) a document
Select a text
Ctrl+c Ctrl+V

**What is the expected behavior?**
Should copy and paste text

**Did this work in previous versions of DocumentServer?**
Don't know...

**DocumentServer version:**
Document Editor Version 6.3.1

**Operating System:**
Ubuntu 21.10

**Browser version:**
94.0

Works in Chromium.
Tester in Firefox from snap, from deb, with cache cleared, and in Troubleshoot mode. Nothing helps.

**Comment by ShockwaveNN** [comment]
Hi, I've got several ideas

I've checked your issue on Ubuntu 20.04 and Firefox 94.0 and copy-paste seems fine for me

So I got several ideas

1. Could you check same server on Ubuntu 20.04? I think Ubuntu 21.10 was released not a long time ago and non-lts releases are usually not very stable and maybe it just broke on Ubuntu 21.10 (we'll recheck if you confirm it)
2. Maybe the reason is that you've using DocumentServer v6.3.1 and we released several versions after that and maybe this issue is fixed, I've check on v6.4.2

**Comment by alci63** [comment]
It indeed works on Firefox 94.0 / Ubuntu 20.04 LTS on the same 6.3.1 server (obviously on another client computer).
In fact I made another test, and it also works on Firefox 94.0 / Ubuntu 21.10 (.deb package) on another user.
So the problem is related to the profile, although I did test after cleaning the cache and in troubleshooting mode...

**Comment by ShockwaveNN** [comment]
Sorry, in that case I have no idea that may be a reason, maybe some extension or maybe some specific setup of your system

**Comment by alci63** [comment]
It's not the plugins, as running in Troubleshooting mode does not solve the problem.
BUT I created a new profile (with about:profiles functionnality of Firefox), and this solves the issue, so it definitely is specific to my legacy profile... I'll delete it and start fresh.
Thanks for your support.
Regards.
