### ISSUE TITLE
Links not clickable in pdf produced from 'download as'

### ISSUE THREAD

**Issue by y0va** [ONLYOFFICE/DocumentServer#189]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Links are not clickable in pdfs produced from 'download as'.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a Hyperlink in OnlyOffice Wordprocesser and click on 'download as' 'pdf'.

**What is the expected behavior?**
I want the destination to be opened in my browser when I click on the link in the document viewer.

**Did this work in previous versions of DocumentServer?**
Don't know.

**DocumentServer version:**
Document Editor Version is 4.3.3

**Operating System:**
Debian Sid

**Browser version:**
Firefox 52.4

**Comment by ShockwaveNN** [comment]
Thank you, this is a known problem.
Currently we have no ETA for fixing it.

**Comment by viniciusov** [comment]
No fix yet? I'm facing this issue too: nothing happens when I click on a hyperlink.

**Comment by Rita-Bubnova** [comment]
Sorry, the problem still not fixed.It is know issue 23458 in our private tracker.
We still got no ETA of fix. You can contact sales team sales@onlyoffice.com to speed up it.

**Comment by viniciusov** [comment]
@Rita-Bubnova but I'm facing this issue when writing a document (.doc)... the right-click on the hyperlink doesn't take me to anywhere.

**Comment by Rita-Bubnova** [comment]
Sorry, I cannot understand part about `.doc`. Could you explain in more details?

**Comment by viniciusov** [comment]
@Rita-Bubnova , I was working in a document with `.docx` extension, like that Microsoft Word standard extension (sorry for my mistake earlier, it's not `.doc`).   
This document contains a hyperlink to a website, but when I hold CTRL and left-click on it, nothing happens.

**Comment by Rita-Bubnova** [comment]
Can you attach file DOCX with problem?

**Comment by viniciusov** [comment]
[Test.docx](https://github.com/ONLYOFFICE/DocumentServer/files/3448158/Test.docx)

Here it is... when I CTRL+click on the link, nothing happens (don't know if it is my system).

**Comment by Rita-Bubnova** [comment]
@viniciusov, this issue talks about links not clickable in PDF. 
I think your problem is not related to this. Please, create a new issue and fill out issue template correctly, especially your browser, operating system and DocumentServer version.

**Comment by viniciusov** [comment]
@Rita-Bubnova , ok I'll create a new issue (I thought this was the same subject: issues with hyperlinks).

**Comment by Rita-Bubnova** [comment]
We know about problem with links in PDF and currently this feature not implemented.
But issues with links in DOCX is something new for us, so we need to explore this issue.

**Comment by cpot** [comment]
> 
> 
> Sorry, the problem still not fixed.It is know issue 23458 in our private tracker.
> 
> This feature require rewrite of our pdf engine, so we still go no ETA... You can contact sales team [sales@onlyoffice.com](mailto:sales@onlyoffice.com) to speed up it.

From sales, can we have a exact quotation and estimated delivery date ? Thank you

**Comment by Rita-Bubnova** [comment]
All contact with sales via email (sales@onlyoffice.com).

**Comment by cpot** [comment]
Any news? Our customers really need this functionality

**Comment by Rita-Bubnova** [comment]
Sorry, no news.

**Comment by Rita-Bubnova** [comment]
> Sorry, no news.

This comment is incorrect.
The issue of not saving links when export to PDF  fixed (https://github.com/ONLYOFFICE/core/commit/1d8860f73e9d0d196b503c17c041dc1cad6de5ec). This fix is only on develop, so it's will be not in v6.0 but in next version.

But the problem of following links in the PDF file, if it is opened in the DocumentServer, persists (issue 23458 in our issue tracker).

**Comment by ShockwaveNN** [comment]
DocumentServer v6.0.0 and DesktopEditors v6.0.0 are released.
This issue should be fixed.

Feel free to comment or create another if got any troubles.

**Comment by jlemangarin** [comment]
Hello @ShockwaveNN,

We tested the fix in 6.1.0 and it does not works :'(

Please find attached out test file

[Répartition scénarios TestRail 3.8.1.xlsx.pdf](https://github.com/ONLYOFFICE/DocumentServer/files/5653714/Repartition.scenarios.TestRail.3.8.1.xlsx.pdf)

**Comment by ShockwaveNN** [comment]
@jlemangarin Please note, that original issue contains 2 not directly related bugs

1. If you download as pdf file in ONLYOFFICE DocumentServer and open in any third-party pdf viewer - links are not clickable. This issue should be fixed
2. If you open any pdf file with link in ONLYOFFICE DocumentServer - PDF Viewer - link are not clickable - this issue is still actual and described in https://github.com/ONLYOFFICE/DocumentServer/issues/1044

**Comment by jlemangarin** [comment]
Hello @ShockwaveNN,

We are in case 1, sorry if I didn't described it well.

It seems that OnlyOffice Desktop Editor is properly formating links when we export a document as PDF. But we mainly use OnlyOffice in it's web-based version (with an Alfresco link) and we use the API [described here](https://api.onlyoffice.com/editors/conversionapi) to export a document as PDF. 

This API seems to be not working with links.

Thanks in advance !

Best,

**Comment by ShockwaveNN** [comment]
@jlemangarin I think it's separate issue so please create new issue and describe api example request your using and example docs (and of course version of DocumentServer and host os)

**Comment by PixiesFR** [comment]
Hi, 

With documentserver onlyoffice-documentserver-ee      7.0.1-37 On ubuntu 18.04.
Still unable to click on link when opening a PDF file with document server.

**Comment by ShockwaveNN** [comment]
@PixiesFR if you trying to click links inside PDF files opened in DocumentServer - this issue is still unresolved and located [here](https://github.com/ONLYOFFICE/DocumentServer/issues/1044)
