### ISSUE TITLE
Editing file removes ContentControl CustomXMLPart binding (dataBinding tag removed on save)

### ISSUE THREAD

**Issue by gpanayotov** [ONLYOFFICE/DocumentServer#2448]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package), Docker

### Version information

7.4, 7.5

### Expected Behavior

When editing a document with content control bound to a Custom XML Part  and saving it the data binding should remain (w:dataBinding tag should remain) and not deleted

### Actual Behavior

After i open a document with w:dataBinding in w:std and changing somethin otside this tag then after save the tag is removed from the new document

the part of the document.xml before editing with the editor is:
```xml
		<w:sdt>
			<w:sdtPr>
				<w:id w:val="2142771203" />
				<w:placeholder>
					<w:docPart w:val="DefaultPlaceholder_-1854013440" />
				</w:placeholder>
				<w:dataBinding w:prefixMappings="xmlns:ns0='https://example.com/template' xmlns:ns1='http://www.w3.org/2001/XMLSchema-instance' " w:xpath="/ns0:Template[1]/ns0:Task[1]/ns0:Title[1]" w:storeItemID="{16BB3F27-6769-43F1-94EF-38FF097B8F79}" />
				<w:text />
			</w:sdtPr>
			<w:sdtContent>
				<w:p w:rsidR="00502058" w:rsidRDefault="00502058" w14:paraId="65D134F2" w14:textId="48E5E0A5">
					<w:r>
						<w:t xml:space="preserve">A.10 Test title</w:t>
					</w:r>
				</w:p>
			</w:sdtContent>
		</w:sdt>
```

After saving the document the part of the xml looks:

```xml
		<w:sdt>
			<w:sdtPr>
				<w15:appearance w15:val="boundingBox"/>
				<w:id w:val="2142771203" />
				<w:placeholder>
					<w:docPart w:val="DefaultPlaceholder_-1854013440" />
				</w:placeholder>
				<w:rPr></w:rPr>
			</w:sdtPr>
			<w:sdtContent>
				<w:p>
					<w:pPr>
						<w:pBdr></w:pBdr>
						<w:spacing />
						<w:ind />
						<w:rPr></w:rPr>
					</w:pPr>
					<w:r>
						<w:t xml:space="preserve">A.10 Test title</w:t>
					</w:r>
					<w:r></w:r>
				</w:p>
			</w:sdtContent>
		</w:sdt>
```

### Reproduction Steps

1. Create a docx file with content contro; field bound to CustomXMLPart or download the following file: [test.docx](https://github.com/ONLYOFFICE/DocumentServer/files/13170246/test.docx)
2. Open the file
3. Change something outside the content control
4. Save the file
5. Check the databinding tag

**Comment by XDmitryK** [comment]
@gpanayotov Hi
Thanks for your feedback, I can confirm this is bug issue #64898

**Comment by uestc-lxp** [comment]
Could you please help to fix this bug? it sames a long time

**Comment by uestc-lxp** [comment]
@XDmitryK @Rita-Bubnova  @gpanayotov Is there some plan to fix this issue?  Thanks

**Comment by TatianaKirillova** [comment]
Hello @uestc-lxp !
I'm happy to report that the issue is fixed in version 8.3.2  Don't miss updates. Have a nice day!

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.3.2 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by uestc-lxp** [comment]
Thanks a lot, you are great

**Comment by uestc-lxp** [comment]
@TatianaKirillova @Rita-Bubnova  I tested the v8.3.2, the issue still exits, after edit and save, the paraId disappear, do you confirm that 8.3.2 has fixed this issue?

![Image](https://github.com/user-attachments/assets/b158d92e-1cfd-4d66-832f-349d8cc4e5f6)

**Comment by uestc-lxp** [comment]
@TatianaKirillova  Thanks for your reply, after saving, is there a unique identifier or a method in the xml that can locate the contents of the original paraid?
