### ISSUE TITLE
Custom doc info field not detected, it remove the custom field on ODT files. 

### ISSUE THREAD

**Issue by lea-aglz** [ONLYOFFICE/DocumentServer#2616]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

8.0.0.99

### Expected Behavior

Fields are correctly recognized. 

### Actual Behavior

The fiels was not detected. When I changed the character string, saved, and reopened it in Libre Office, the filed was not detected, and the custom property that I had set up earlier had disappeared.

### Reproduction Steps

1. I created a ODT file with LibreOffice. The tab to set a custom property is found in File > Properties > Custom Properties : 
![293652610-b6138310-28c1-47cd-b796-909effcbcd9e](https://github.com/ONLYOFFICE/DesktopEditors/assets/147405594/c0fd68d7-fa09-404f-9be5-0a2cf6e4b088)

2. Insert > Field > Other fields (Ctrl + F2) > Document info tab : Select the newly created custom property to display it in the document

![293652752-4123e532-bebf-48fe-a4b9-c97a79507fc8](https://github.com/ONLYOFFICE/DesktopEditors/assets/147405594/502203e5-e59c-4bcc-bd48-61bc9d02325d)

3. After saving the docx file and opening with Only Office. The fiels was not detected : 
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/147405594/12d3771e-72ea-4c6f-930b-9ffc087b3f35)

4. When I saved, and reopened it in Libre Office, the filed was not detected, and the custom property that I had set up earlier had disappeared.

### Additional information

This problem only occurs with ODT docucments, not DOCX.

**Comment by maruacat** [comment]
Hello @lea-aglz 
We have fixed this problem https://github.com/ONLYOFFICE/core/commit/9bb45aa05d9cbc1c79e80304bfa047bc0a9fc60d. The fix will be available after the release of the new version 8.1.0
Thanks for your help!

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by adminceovision** [comment]
Hello,

After some retest the custom field in the .odt file now displays as a field in OnlyOffice, which is a progress:

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/172752773/eeeb46f6-992d-47e4-ad4d-6bb4fe69a133)

But I still have the other issue: after editing the file in OnlyOffice, when I open it again with LibreOffice, the custom property entirely disappears and the field value has become plain text.

Am I missing something?

Thanks,

**Comment by Rita-Bubnova** [comment]
@adminceovision, We think it's two separate problems, so please create new issue.
