### ISSUE TITLE
CSV import does not preserve characters and loses data

### ISSUE THREAD

**Issue by Beep6581** [ONLYOFFICE/DocumentServer#3085]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package), Linux (RPM package)

### Version information

8.2.2.22

### Expected Behavior

Data imported from CSV should be preserved. When using "Text" formatting it should be 100% identical with the source.

### Actual Behavior

Data is forcefully reformatted according to some guessed data type, leading to loss of data.

### Reproduction Steps

Example CSV:
```
0000000000000001;Foo
100000000000000;Bar
1990/01/02;Baz
1234/56/78;Cow
```

1. Open CSV in OpenOffice.
2. The "Choose CSV options" dialog shows the correct values. Hit ok.
3. The imported values have been reformatted and data is lost. When I select formatting to "Text" I expect data to be 100% identical.

### Additional information

![Screenshot_20250108_101251](https://github.com/user-attachments/assets/3a5c7f48-c1f8-4755-b3a9-9381499f5447)
![Screenshot_20250108_101140](https://github.com/user-attachments/assets/6f5e6ee8-ccc0-4c7a-9b6b-b1f38bd47033)

**Comment by VladimirProkofiev52** [comment]
Hello!
@Beep6581 In your report, you describe several issues:

1. The values in the preview window differ from the values in the table cells after conversion—this is a known bug 46459.

2. Dates are being converted into numbers—we recently implemented fixes for this issue, and it should be resolved in the next version of our editor.

3. Values are automatically converted after opening a CSV file—this is an enhancement 72575.

In the future, please create a separate report for each issue. 
For now, let's use this thread to focus on the improvement related to value conversion.

Thank you very much for report!

**Comment by MerlinBlatterer** [comment]
How is this not fixed yet?

This STUPID behaviour. Data just being interpreted willy nilly.
"this date? lets interpret it american style on one line european style on the next"
"oh this time? lets make a date out of that."

Just give me the option to import everything as text or general type. and let me decide what type a column should be after the fact.
I just absoloutly HATE the program automatically interpreting type.

**Comment by Beep6581** [comment]
Hello!

@VladimirProkofiev52 are you an AI? Because you use em-dashes, have no publicly visible contributions on GitHub, and seem to hallucinate.

> The values in the preview window differ from the values in the table cells after conversion—this is a known bug 46459.

I did not report that. And there is no #46459 in this repo.

> Values are automatically converted after opening a CSV file—this is an enhancement 72575.

#72575 does not exist, no idea what you're referencing.

> In your report, you describe several issues: (...) In the future, please create a separate report for each issue.

No, I described one issue: imported data should be 100% identical with the source when using "text" formatting. If you choose to break that up into several issues which don't exist, that is on you. I know all about one-problem-per-issue, I even wrote a guide on the subject. Please don't pester someone who took time to write a proper bug report with arbitrary references to non-existent issues. Or do you expect people to look through [all 268](https://github.com/orgs/ONLYOFFICE/repositories) of your repositories?

And this is a bug report, not a feature request. The feature is the broken data conversion and auto-formatting that the importer currently does. Not converting data and not auto-formatting is the baseline. Importing data is simply broken.

**Comment by VladimirProkofiev52** [comment]
Hello! 
@Beep6581 Regarding the references in my previous response: the bug numbers I mentioned are internal tracking IDs used by our team. They are not publicly accessible. They allow us to track the corresponding issues and their status internally.

I provided the details to explain which parts of the reported behavior are already known to us.

At the moment, this issue is not a priority for our team. If you require an urgent solution, please contact us at sales@onlyoffice.com.

I'm a real person. Let's keep the discussion focused on the issue itself.
