### ISSUE TITLE
RTL mode: Table is still LTR when it is copied from another program

### ISSUE THREAD

**Issue by akram1** [ONLYOFFICE/DocumentServer#3133]
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

8.3

### Expected Behavior

1- When copying/paste or creating RTL table, OnlyOffice should be able to detect it is RTL or LTR table and apply correct Table representation. 
2- When table is highlighted, RTL/LTR options from Show Advanced settings should be able to switch table direction.
3- RTL/LTR options from Show Advanced should work at object level, not text. When text is RTL/LTR options from Show Advanced, it changes text direction. When a table or other object is highlighted, it changes object direction, not its content.  

### Actual Behavior

When copying/paste or creating RTL table, OnlyOffice copies it as LTR table. Applying RTL properties from Advanced Settings changes some letters in the table, not the table orientation. 

![Image](https://github.com/user-attachments/assets/9052928e-cea6-4b72-a288-99b342f58844)

### Reproduction Steps

Copy/paste RTL table from LibreOffice or MS Word.
Create a table

**Comment by ElenaMaaya** [comment]
Hello @akram1 !
Thank you for report!
This is a known bug 69579.

**Comment by akram1** [comment]
Also, Table is missing orientation. 
The starting point of table is the first cell on the top left. 
Key nevigation (Left arrow, right arrow, tab) still LTR. I think the solution is table should have LRT/RTL property to fix the orientation and copy/paste problem

**Comment by ramezrafla** [comment]
Thanks @akram1 for taking the initiative and reporting all these issues so the team can fix.
Very excited @Rita-Bubnova @ElenaMaaya for the amazing progress! Thank you!

In the same screenshot, I wanted to point the team's attention to this letter rendering:

![Image](https://github.com/user-attachments/assets/66b01c4b-7a28-48b0-b113-ba9f5ac075b0)

The combination of 'lam-alef' needs to be automatically replaced with the appropriate character

![Image](https://github.com/user-attachments/assets/b3d99438-bffd-45e1-882b-8fbc6960aaf3)

This also applies to 'lam-alef_with_hamza' like this:

![Image](https://github.com/user-attachments/assets/681a3497-f4ce-434a-8ec3-222d7dcc9ea7)

This is an artifact from the fact that OnlyOffice does its own rendering in canvas (vs other doc editors that use the underlying editors in the browser)

**Comment by akram1** [comment]
[new.docx](https://github.com/user-attachments/files/20847107/new.docx)

[onlyoffice doc copy paste.odt](https://github.com/user-attachments/files/20847108/onlyoffice.doc.copy.paste.odt)

Version 9.0 update:
This issue is still present in version 9.0. It consists of 2 parts. OnlyOffice does not recognize RTL/LTR when pasting formatted text. So when pasting RTL table or simple RTL text like numbered text, LTR is applied. Second part, Table object has no RTL/LTR properties. I provided 2 files: one created by LibreOffice odt file, the second OnlyOffice I created docx I copied from LibreOffice. You can examine the issue with live data.
-

**Comment by ElenaMaaya** [comment]
Dear users, @ramezrafla, @akram1! 

Thank you for taking the time to provide us with your feedback. We truly appreciate your input and value your contributions to improving our product.

We would like to confirm that we are aware of the issue with tables in DOCX files. Our development team is actively working on resolving this problem.

@ramezrafla, regarding the «lam-alef» display issue, we would like to inform you that this problem has been successfully addressed in version 8.3.3 and does not occur in the latest release. You can find more details about this in [issue](https://github.com/ONLYOFFICE/DocumentServer/issues/3115).

If you are still experiencing any problems with «lam-alef» display or encounter any other issues, please create a new support ticket. In your report, please describe the scenario in detail and attach a test file that demonstrates the problem. This will help us investigate and resolve the issue more efficiently.

Thank you for your understanding and cooperation.

**Comment by akram1** [comment]
Dear Elena Maaya
Regarding the «lam-alef». It has been fixed in 8.3.3 and 9.0. I did not notice any problem since. Regarding the table problem, I updated the issue in my last post. Download LibreOffice v25 and OnlyOffice v9.0 files to test and check with live data. This helps better in debugging and fixing the issue. I think OnlyOffice team has made most of the RTL and Arabic requirements. Fewer issues remain to be resolved, and hopefully they will be fixed in the coming versions of 9.1+. With 3 iterations every year and year-to-year of one major version, OnlyOffice is progressing faster than any other software. Good work OnlyOffice.

**Comment by akram1** [comment]
Update version 9.0:
I think this is related to copied table.
The direction of copied text from Arabic websites is not maintained and treated as LTR text. As a result, the direction LTR but 
1- regular text is right aligned 
2- titles and numbering and bullets are left aligned LTR
3- Direction Left/right arrow keys are swapped  (same result when copying tables)

I do not know whether you can determine the RTL/LTR of copied all the time. But a quick solution is to apply the direction LTR/RTL of the line where the copied text is pasted.

<img width="1298" height="688" alt="Image" src="https://github.com/user-attachments/assets/70cbe2b1-90db-4eff-abb1-be462124dd8d" />

**Comment by akram1** [comment]
Update version 9.0.4:
The issues mentioned are still present in version 9.0.4. Please fix them

**Comment by akram1** [comment]
Update version 9.1:
The issue is still present in version 9.0.4. Please fix it. Same problem is applied for Smart Art. Table and Smart Art object should have RTL/LTR property to switch object orientation, not just for text direction only.

**Comment by ElenaMaaya** [comment]
Hello, @akram1! Thank you for your feedback! Work on this functionality is underway, but exact timelines are not available yet.

**Comment by carolinafain16** [comment]
I am also experiencing this issue in the Presentation editor. Tables in RTL documents that were created in MS Office are displayed in reverse, which makes it very difficult to create professional slide decks. This is a critical feature for our workflow.
