### ISSUE TITLE
fonts not found

### ISSUE THREAD

**Issue by djibythiaw** [ONLYOFFICE/DocumentServer#92]
Hi,
I've installed the last version of document server on debian 8. When i launch the client, i've an error saying that fonts are missing. Below are the errors that i have in console
GET http://10.42.2.110/2017-03-07-13-37/fonts/odttf/qphs4auxpoz8e7dg.js 404 (Not Found)
 GET http://10.42.2.110/2017-03-07-13-37/fonts/odttf/q7wsh35rpfzgqmuwqtuy.js 404 (Not Found)
GET http://10.42.2.110/2017-03-07-13-37/fonts/odttf/cposa4mnqjwsamuwqtuy.js 404 (Not Found)
GET http://10.42.2.110/2017-03-07-13-37/fonts/odttf/cposa4mnqjwsa4jqqt4gc.js 404 (Not Found)
GET http://10.42.2.110/2017-03-07-13-37/fonts/odttf/epywa1knkjr1hinwea.js 404 (Not Found)
GET http://10.42.2.110/2017-03-07-13-37/fonts/odttf/epywa1knkjrw1m1wktdy.js 404 (Not Found)
GET http://10.42.2.110/2017-03-07-13-37/fonts/odttf/epywa1knkjrwrm1wktdy.js 404 (Not Found)
GET http://10.42.2.110/2017-03-07-13-37/fonts/odttf/epywa1knkjriwm1wktdy.js 404 (Not Found)
GET http://10.42.2.110/2017-03-07-13-37/web-apps/apps/documenteditor/main/resources/help/fr/Contents.json 404 (Not Found)

When i am editing the document i can't change the font. The listbox to choose a font is empty.

Thanks

**Comment by ShockwaveNN** [comment]
@djibythiaw Seems that you have some troubles while generating font files
See logs in `/var/log/onlyoffice/documentserver` (don't quite remember which file exactly, likely `/var/log/onlyoffice/documentserver/docservice/out.log` or `/var/log/onlyoffice/documentserver/converter/out.log`)
I prety sure there will be some kind error with accessing some files in `/usr/share/fonts` you should fix this error and run
`documentserver-generate-allfonts.sh`

**Comment by djibythiaw** [comment]
I run the script documentserver-generate-allfonts.sh and all works fine now. thanks

**Comment by FeitianSmartcardReader** [comment]
@ShockwaveNN  Hi Sir

I got same issue, but after I do run documentserver-generate-allfonts.sh, the error still exist, do you know where is wrong?
![onlyoffice error](https://user-images.githubusercontent.com/9547938/35800780-f4f7fc3c-0aa4-11e8-963f-3786e62e9824.png)

**Comment by ShockwaveNN** [comment]
@FeitianSmartcardReader probably some permission problem with access to `/usr/share/fonts`, see `/var/log/onlyoffice/documentserver/docservice/out.log` or other logs for some errors

**Comment by FeitianSmartcardReader** [comment]
Thanks for your fast reply, let me check now. ;-)

**Comment by FeitianSmartcardReader** [comment]
@ShockwaveNN did try, i don't think it is a error for permission.
![image](https://user-images.githubusercontent.com/9547938/35812115-13a7a31e-0acb-11e8-84cd-9db5acd9c221.png)

**Comment by FeitianSmartcardReader** [comment]
I did check the log, error say:
[2018-02-05 10:43:36.745] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[2018-02-05 15:13:24.524] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2018-02-05 15:13:24.536] [WARN] nodeJS - update cluster with 1 workers
[2018-02-05 15:13:24.543] [WARN] nodeJS - worker 5085 started.
[2018-02-05 15:13:24.544] [WARN] nodeJS - update cluster with 1 workers
[2018-02-05 15:13:24.690] [WARN] nodeJS - Express server starting...
[2018-02-05 15:13:25.314] [ERROR] nodeJS - error init:^M
Error: ENOENT: no such file or directory, stat '/usr/share/fonts/cmap/Identity-H'
    at Error (native)
[2018-02-05 15:13:25.480] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[2018-02-05 15:16:02.413] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2018-02-05 15:16:02.478] [WARN] nodeJS - update cluster with 1 workers
[2018-02-05 15:16:02.504] [WARN] nodeJS - worker 447 started.
[2018-02-05 15:16:02.505] [WARN] nodeJS - update cluster with 1 workers
[2018-02-05 15:16:03.354] [WARN] nodeJS - Express server starting...
[2018-02-05 15:16:06.998] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2018-02-05 15:16:07.020] [WARN] nodeJS - update cluster with 1 workers
[2018-02-05 15:16:07.027] [WARN] nodeJS - worker 494 started.
[2018-02-05 15:16:07.027] [WARN] nodeJS - update cluster with 1 workers
[2018-02-05 15:16:07.164] [WARN] nodeJS - Express server starting...
[2018-02-05 15:16:07.767] [ERROR] nodeJS - error init:^M
Error: ENOENT: no such file or directory, stat '/usr/share/fonts/cmap/Identity-H'
    at Error (native)
[2018-02-05 15:16:07.887] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[2018-02-05 15:43:44.447] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2018-02-05 15:43:44.462] [WARN] nodeJS - update cluster with 1 workers
[2018-02-05 15:43:44.469] [WARN] nodeJS - worker 1116 started.
[2018-02-05 15:43:44.469] [WARN] nodeJS - update cluster with 1 workers
[2018-02-05 15:43:44.638] [WARN] nodeJS - Express server starting...
[2018-02-05 15:43:45.347] [ERROR] nodeJS - error init:^M
Error: ENOENT: no such file or directory, stat '/usr/share/fonts/cmap/Identity-H'
    at Error (native)
[2018-02-05 15:43:45.466] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode

**Comment by ShockwaveNN** [comment]
@FeitianSmartcardReader 
yeah, it's because `/usr/share/fonts/cmap` have some symbolic links in it (which are not working inside docker image, they link to non-existing files in container).
It's a known problem (bug #32683 in our internal bugtracker).
One of the way to fix it - do not use docker mount like `-v /usr/share/fonts:/usr/share/fonts` and create folder `/usr/share/fonts/custom` in host machine and mount this folder.
Or found out about `/usr/share/fonts/cmap` and remove symbolic links in it

**Comment by FeitianSmartcardReader** [comment]
@ShockwaveNN Yes, i found it too, and I do remove the symbolic links, the whole folder was removed.

And now, I am reboot my computer to try, I back to you later, thanks for your fast reply. ;-)

**Comment by FeitianSmartcardReader** [comment]
based on the error in log:
1. nodeJS - error init:^M - fixed, some files had ^M in linux
2. Error: ENOENT: no such file or directory, stat '/usr/share/fonts/cmap/Identity-H'
at Error (native) - fixed, remove cmap folder and running document-generate-allfonts.sh


it always give below error, like "odttf/*.js not found", do you know what's that means?
http://122.70.148.35:8099/2017-08-11-08-40/fonts/odttf/qphs4auxpoz8e7dg.js

And this time, i check the log:
![image](https://user-images.githubusercontent.com/9547938/35814405-f4a07b02-0ad0-11e8-83c5-8175e19bd16f.png)

**Comment by ShockwaveNN** [comment]
@FeitianSmartcardReader according to log everything should be fine, could you check browser cache, clean it (or use incognito mode).

**Comment by FeitianSmartcardReader** [comment]
@ShockwaveNN Yes, I do using my phone and do login for test, but the error still. so strange.
still give same error in https://user-images.githubusercontent.com/9547938/35800780-f4f7fc3c-0aa4-11e8-963f-3786e62e9824.png

**Comment by FeitianSmartcardReader** [comment]
@ShockwaveNN  thanks for your help, do you know where call odttf? I don't have this folder, so where this from?

**Comment by ShockwaveNN** [comment]
presence of `odttf` is normale
Could you create new docker container? I strongly think this have something to do with cache

**Comment by FeitianSmartcardReader** [comment]
@ShockwaveNN yes, u r right. there have something wrong in my docker, and I do reboot it, now it works.

Really thanks for that. And another questions, for chinese fonts support, do you have any idea to support that?

**Comment by FeitianSmartcardReader** [comment]
@ShockwaveNN  using below command solve the issue:

First, I do copy windows fonts into /usr/share/fonts/windows-fonts

tar cv * | docker exec -i 6fc16dba5bc0 tar x -C /usr/share/fonts/
docker exec onlyoffice-document-server documentserver-generate-allfonts.sh

**Comment by ShockwaveNN** [comment]
@FeitianSmartcardReader so am I right that you solved all your problems with fonts?

**Comment by FeitianSmartcardReader** [comment]
@ShockwaveNN Yes, all issues solved now. Thanks, ;-)

**Comment by falling-star** [comment]
![image](https://user-images.githubusercontent.com/3634908/44034285-58e6cccc-9f2a-11e8-8ae6-696d667be8a9.png)

We are not able to load various fonts on OSX 10.13.2 and Chrome Version 67.0.3396.99 (Official Build) (64-bit). 

Details : 
- Document Server - 5.1.5 / centos
- Client - OSX 10.13.2 and Chrome Version 67.0.3396.99

@ShockwaveNN I have tried installing msttcore-fonts-installer-2.6-1 again and run documentserver-generate-allfonts.sh , but issue still exists. How can we properly re-install all the default fonts on centos ?

**Comment by ShockwaveNN** [comment]
@falling-star please clean cache of your browser, run `documentserver-generate-allfonts.sh` again and look for logs in `/var/log/onlyoffice/documentserver/` for any errors, probably access problems to fonts files

**Comment by falling-star** [comment]
<img width="1440" alt="screen shot 2018-08-13 at 7 31 58 pm" src="https://user-images.githubusercontent.com/3634908/44036554-abc29890-9f2f-11e8-9d55-259cdb36cfbe.png">

@ShockwaveNN Thank you for quick reply. Seems like some fonts are missing from DIR='/var/www/onlyoffice/documentserver/fonts' (see attached image).

I already installed msttcore-fonts-installer-2.6-1 . please see attached image below.
<img width="1440" alt="screen shot 2018-08-13 at 7 39 31 pm" src="https://user-images.githubusercontent.com/3634908/44036931-abeb65c6-9f30-11e8-8c01-e2eff2f90a3a.png">

Let me know what could be the issue ?

**Comment by ShockwaveNN** [comment]
@falling-star what is content of `/var/log/onlyoffice/documentserver/docservice/out.log`
it's very strange that server require font by name, times.ttf, not by it's id

**Comment by falling-star** [comment]
@ShockwaveNN Yeah, In earlier versions (5.1.4), I didn't see this issue. 

I don't see any error logs in /var/log/onlyoffice/documentserver/docservice/out.log OR err.log.

[2018-08-13 14:17:40.086] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2018-08-13 14:17:40.096] [WARN] nodeJS - update cluster with 1 workers
[2018-08-13 14:17:40.102] [WARN] nodeJS - worker 32479 started.
[2018-08-13 14:17:40.493] [WARN] nodeJS - Express server starting...
[2018-08-13 14:17:40.933] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[2018-08-13 14:24:14.106] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2018-08-13 14:24:14.117] [WARN] nodeJS - update cluster with 1 workers
[2018-08-13 14:24:14.123] [WARN] nodeJS - worker 648 started.
[2018-08-13 14:24:14.511] [WARN] nodeJS - Express server starting...
[2018-08-13 14:24:14.950] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode

**Comment by ShockwaveNN** [comment]
@falling-star are you 100% sure your browser cache is clear? Could you try another browser?

**Comment by falling-star** [comment]
@ShockwaveNN After disabling the cache in chrome (attached error screenshots).

<img width="626" alt="screen shot 2018-08-14 at 7 16 18 am" src="https://user-images.githubusercontent.com/3634908/44067226-146f1ece-9f92-11e8-8bdf-0831f31ca355.png">
<img width="652" alt="screen shot 2018-08-14 at 7 16 05 am" src="https://user-images.githubusercontent.com/3634908/44067227-14bef304-9f92-11e8-925c-d941595880c4.png">

**Comment by ShockwaveNN** [comment]
@falling-star Ok, our dev team have no idea how this happened. Fonts should not be named like `arial.ttf` in any cases.
They can be named like `fonts/odttf/qphs4auxpoz8e7dg.js` in old version of DocumentServer, and currently named like `fonts/628`
I suggest backup all your user data, delete all configs and reinstall application

**Comment by falling-star** [comment]
@ShockwaveNN We had re-installed already but couldn't resolve the issue. 

Files seem to be loading fine in MacOS browsers (font/<number>) but fail in Win7/10 Browsers (font/<font_name>). If you see any platform related hint as to why it might happen, please let us know.

**Comment by ShockwaveNN** [comment]
@falling-star did you try different pc with Win7? Maybe it some kind of group policy for some security reason, it's very unlikely, that this issue have different  behavior on Mac and Windows

**Comment by falling-star** [comment]
@ShockwaveNN Everything seems to work now. Issue was happening in a specific env here. I am still not sure of the root cause, will definitely update here if I find any. Thanks a lot.
